### ISSUE TITLE
Chat with gdoc

### ISSUE THREAD

**Issue by dav1303** [taers232c/GAMADV-XTD3#359] opened 2023-05-05 09:35 UTC
Hi Ross

When I use this command am create chatmessage space spaces/AAAAJQd_pxI gdoc user@domain.com name "XXX Installation" I get all the text but unfortunatly the images which are in the doc file are lost in the chat message

thanks

**Comment by jay-eleven** [comment] 2023-05-07 14:43
Closing, duplicate of #360

**Closed by jay-eleven** 2023-05-07 14:43 UTC
